version: '3.1'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    command: ["/bin/runWebserver.sh"]
  worker:
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      TWEET_LAST_TWEETS: 1000
      TWEET_EVERY_MINUTES: 1
      TWEET_QUERY: "news"
    command: ["/bin/runPeriodic.sh"]
  mongo:
    image: mongo:4.0
